services:
#    rmc_symfony_classroom.example:
#        class: RMC\SymfonyClassroomBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    rmc_createBike.form.type.bike:
        class: RMC\SymfonyClassroomBundle\Form\Type\BikeType
        tags:
            - { name: form.type, alias: createBike }
