# RMC/SymfonyClassroomBundle/Resources/config/validation.yml
RMC\SymfonyClassroomBundle\Entity\Bike:
    properties:
        name:
            - NotBlank: ~
        price:
            - NotBlank: ~
            - Type: float
        description:
            - NotBlank: ~